/*Write a program to return all the characters in a string using the user-defined method,  compare the result with the String built-in toCharArray() method, and display the result
Hint => 
Take user input using the  Scanner next() method to take the text into a String variable
Write a method to return the characters in a string without using the toCharArray() 
Write a method to compare two string arrays and return a boolean result
In the main() call the user-defined method and the String built-in ​​toCharArray() method, compare the 2 arrays, and finally display the result
*/


import java.util.Scanner;

public class CharArray{
	
	//Method to create char array using toCharArray() method
	public static char[] usingToCharArray(String str){
		char arr1[] = str.toCharArray();
		return arr1;
	}
	
	//Method to create char array using user-define method() method	
	public static char[] usingUserDefine(String str){
		char arr2[] = new char[str.length()];
		for(int i=1; i<str.length(); i++){
			arr2[i] = str.charAt(i);
		} 
		return arr2;
	}

	//Method to compare two strings
	public static Boolean compare(char arr1[], char arr2[]){
		for(int i=0; i<arr1.length; i++){
			if(arr1[i] == arr2[i]){
				return true;
			}
		}
		return false;
	}
		

	public static void main(String[] args){
		//Taking Inputs
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter a string");
		String str = sc.next();
		
		//Calling methods
		char arr1[] = usingToCharArray(str);
		char arr2[] = usingUserDefine(str);

		//Print result
		System.out.println("Char arrays generated by both method are Equal : " + compare(arr1,arr2));
		sc.close();
	}
}