/*Write a program to create a substring from a String using the charAt() method. Also, use the String built-in method substring() to find the substring of the text. Finally Compare the the two strings and display the results
Hint => 
Take user input using the  Scanner next() method to take the String variable and also the start and the end index to get the substring from the given text
Write a method to create a substring from a string using the charAt() method with the string, start, and end index as the parameters
Write a method to compare two strings using the charAt() method and return a boolean result
Use the String built-in method substring() to get the substring and compare the two strings. And finally display the result
*/


import java.util.Scanner;

public class SubStrings{
	
	//Method to extract substring using charAt() method
	public static String subStrCharAt(String str, int start, int end){
		String sub = "";
		for(int i=0; i<end; i++){
			sub += str.charAt(i);
		}
		return sub;
	}
	
	//Method to extract substring using in-built substring() method	
	public static String subString(String str, int start, int end){
		String result = str.substring(start,end);
		return result;
	}

	//Method to compare two strings
	public static Boolean compare(String s1, String s2){
		if(s1.equals(s2)){
			return true;
		}
		return false;
	}
		

	public static void main(String[] args){
		//Taking Inputs
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter first string");
		String str = sc.next();
		System.out.println("Enter start index");
		int start = sc.nextInt();
		System.out.println("Enter end index");
		int end = sc.nextInt();
	
		//Calling methods
		String s1 = subString(str,start,end);
		String s2 = subStrCharAt(str,start,end);

		//Print result
		System.out.println("Original string is : " + str);
		System.out.println("Substrings are : " + s1 + "	" + s2);
		System.out.println("Substring generated by both method are Equal : " + compare(s1,s2));
		sc.close();
	}
}